
import java.io.IOException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author root
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        informationPanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        authorLabel = new javax.swing.JLabel();
        container = new javax.swing.JPanel();
        modeLabel = new javax.swing.JLabel();
        modeComboBox = new javax.swing.JComboBox<>();
        locationLabel = new javax.swing.JLabel();
        locationComboBox = new javax.swing.JComboBox<>();
        deepNeuralNetworkButton = new javax.swing.JButton();
        tensorboardButton = new javax.swing.JButton();
        buttonPanel = new javax.swing.JPanel();
        submit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Deep Learning for Tropospheric Ozone Prediction");

        authorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        authorLabel.setText("Ashish D'Souza, Engineering Design Technology");

        javax.swing.GroupLayout informationPanelLayout = new javax.swing.GroupLayout(informationPanel);
        informationPanel.setLayout(informationPanelLayout);
        informationPanelLayout.setHorizontalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(authorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        informationPanelLayout.setVerticalGroup(
            informationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informationPanelLayout.createSequentialGroup()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorLabel))
        );

        container.setLayout(new java.awt.GridLayout(3, 2, 10, 10));

        modeLabel.setText("Mode:");
        container.add(modeLabel);

        modeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Evaluate", "Predict" }));
        modeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeComboBoxActionPerformed(evt);
            }
        });
        container.add(modeComboBox);

        locationLabel.setText("Location:");
        container.add(locationLabel);

        locationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "New Castle County" }));
        locationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationComboBoxActionPerformed(evt);
            }
        });
        container.add(locationComboBox);

        deepNeuralNetworkButton.setText("Deep Neural Network");
        deepNeuralNetworkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deepNeuralNetworkButtonActionPerformed(evt);
            }
        });
        container.add(deepNeuralNetworkButton);

        tensorboardButton.setText("TensorBoard");
        tensorboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tensorboardButtonActionPerformed(evt);
            }
        });
        container.add(tensorboardButton);

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        buttonPanel.add(submit);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        buttonPanel.add(reset);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        buttonPanel.add(exit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(informationPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(container, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        modeComboBox.setSelectedIndex(0);
        locationComboBox.setSelectedIndex(0);
        submit.setEnabled(false);
        reset.setEnabled(false);
    }//GEN-LAST:event_resetActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        if(modeComboBox.getSelectedItem().equals("Evaluate")) {
            resetActionPerformed(evt);
            this.setVisible(false);
            MTD.evaluate.setVisible(true);
        }
        else {
            resetActionPerformed(evt);
            this.setVisible(false);
            System.out.println("I haven't done that part yet.");
            System.exit(0);
        }
    }//GEN-LAST:event_submitActionPerformed

    private void modeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeComboBoxActionPerformed
        // TODO add your handling code here:
        JComboBox[] comboBoxes = {modeComboBox, locationComboBox};
        if (checkComboBoxes(comboBoxes)) {
            submit.setEnabled(true);
            reset.setEnabled(true);
        } else {
            submit.setEnabled(false);
            reset.setEnabled(false);
        }
    }//GEN-LAST:event_modeComboBoxActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Thank you for using this program.\n"
                + "Please continue to support open-source software by sharing "
                + "this project's GitHub repository at "
                + "\"https://computer-geek64.github.io/MTD/\"", "Thank you!",
                JOptionPane.INFORMATION_MESSAGE);
        this.setVisible(false);
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void locationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationComboBoxActionPerformed
        // TODO add your handling code here:
        JComboBox[] comboBoxes = {modeComboBox, locationComboBox};
        if (checkComboBoxes(comboBoxes)) {
            submit.setEnabled(true);
            reset.setEnabled(true);
        } else {
            submit.setEnabled(false);
            reset.setEnabled(false);
        }
    }//GEN-LAST:event_locationComboBoxActionPerformed

    private void deepNeuralNetworkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deepNeuralNetworkButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,
                "<html><img src=\"file:///root/NetBeansProjects/MTD/src/MTD/src/java/image.png\"/></html>",
                "Deep Neural Network", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_deepNeuralNetworkButtonActionPerformed

    private void tensorboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tensorboardButtonActionPerformed
        // TODO add your handling code here:
        try {
            Runtime.getRuntime().exec("firefox-esr localhost:6006");
        }
        catch(IOException ex) {
            JOptionPane.showMessageDialog(null, "An error occurred. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tensorboardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    private boolean checkComboBoxes(JComboBox[] comboBoxes) {
        for (int i = 0; i < comboBoxes.length; i++) {
            if (comboBoxes[i].getSelectedIndex() == 0) {
                return false;
            }
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel authorLabel;
    public javax.swing.JPanel buttonPanel;
    public javax.swing.JPanel container;
    public javax.swing.JButton deepNeuralNetworkButton;
    public javax.swing.JButton exit;
    public javax.swing.JPanel informationPanel;
    public javax.swing.JComboBox<String> locationComboBox;
    public javax.swing.JLabel locationLabel;
    public javax.swing.JComboBox<String> modeComboBox;
    public javax.swing.JLabel modeLabel;
    public javax.swing.JButton reset;
    public javax.swing.JButton submit;
    private javax.swing.JButton tensorboardButton;
    public javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
